volumes:
  db_data:

x-shared_environment: &shared_environment
  LOG_LEVEL: ${LOG_LEVEL:-debug}
  DATABASE_HOST: ${DATABASE_HOST}
  DATABASE_NAME: ${DATABASE_NAME}
  DATABASE_USERNAME: ${DATABASE_USERNAME}
  DATABASE_PASSWORD: ${DATABASE_PASSWORD}
  DATABASE_PORT: ${DATABASE_PORT}
  CURRENT_ENVIRONMENT: ${CURRENT_ENVIRONMENT}
  
services:
  app_dev:
    volumes:
      - ./:/app/
      - /app/.build
    build:
      context: .
      dockerfile: ./DevDockerfile
    environment:
      <<: *shared_environment
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '${DEV_CONTAINER_PORT}:${DEV_CONTAINER_PORT}'
  app:
    image: backend:latest
    build:
      context: .
    environment:
      <<: *shared_environment
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '80:8080'
    restart: always
    # deploy:
    #   mode: global
    #   resources:
    #     limits:
    #       cpus: '1'
    #       memory: '1gb'
    #     reservations:
    #       cpus: '0.25'
    #       memory: '400m'
  migrate:
    image: backend:latest
    build:
      context: .
    environment:
      <<: *shared_environment
    depends_on:
      - db
    command: ["migrate", "--yes"]
    deploy:
      replicas: 0
  revert:
    image: backend:latest
    build:
      context: .
    environment:
      <<: *shared_environment
    depends_on:
      - db
    command: ["migrate", "--revert", "--yes"]
    deploy:
      replicas: 0
  db:
    image: postgres:16-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $DATABASE_USERNAME -d $DATABASE_NAME"]
      interval: 5s
      timeout: 10s
      retries: 120
    volumes:
      - db_data:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - '${DATABASE_PORT}:5432'
    restart: always
    # deploy:
    #   mode: global
    #   resources:
    #     limits:
    #       cpus: '0.5'
    #       memory: '1gb'
    #     reservations:
    #       cpus: '0.25'
    #       memory: '400m'