name: Code Qualty Checks (Linting & Formatting)

on:
  push:
    branches-ignore:
      - develop
      - release/staging
      - release/production

jobs:
  run-lint:
    name: Run SwiftLint
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up environment
        run: |
          echo "Running on branch: $GITHUB_REF"
          alias swiftlint="/opt/homebrew/bin/swiftlint"

      - name: Install NodeJS Dependencies
        uses: bahmutov/npm-install@v1

      - name: Install SwiftLint
        run: |
            npm run install:swiftlint

      - name: Run SwiftLint
        run: |
          npm run lint
  run-formatting-lint:
    name: Run SwiftFormat Lint
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up environment
        run: |
          echo "Running on branch: $GITHUB_REF"
          alias swiftformat="/opt/homebrew/bin/swiftformat"

      - name: Install NodeJS Dependencies
        uses: bahmutov/npm-install@v1

      - name: Install SwiftFormat
        run: |
            npm run install:swiftformat

      - name: Run SwiftFormat Lint
        run: |
          npm run format:lint
