name: Code Qualty Checks (Linting & Formatting)

on:
  push:
    branches-ignore:
      - develop
      - release/staging
      - release/production

jobs:
  run-lint:
    runs-on: macos
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up environment
        run: |
          echo "Running on branch: $GITHUB_REF"
          alias swiftlint="/opt/homebrew/bin/swiftlint"

      - name: Install NodeJS Dependencies
        uses: bahmutov/npm-install@v1

      - name: Install swiftlint
        run: |
            npm run install:swiftlint

      - name: Run swiftlint
        run: |
          npm run lint
  run-formatting-lint:
    runs-on: macos
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up environment
        run: |
          echo "Running on branch: $GITHUB_REF"
          alias swiftformat="/opt/homebrew/bin/swiftformat"

      - name: Install NodeJS Dependencies
        uses: bahmutov/npm-install@v1

      - name: Install swiftformat
        run: |
            npm run install:swiftformat

      - name: Run swiftformat lint
        run: |
          npm run format:lint
