name: CLOC Codebase

on:
  push:
    branches-ignore:
      - develop
      - release/staging
      - release/production

jobs:
  cloc:
    runs-on: macos
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up environment
        run: |
          echo "Running on branch: $GITHUB_REF"
          alias swiftlint="/opt/homebrew/bin/swiftlint"

      - name: Run CLOC
        run: |
          brew install cloc
          cloc .
