name: Fly Deploy to Production
on:
  push:
    branches:
      - release/production

env:
  FLY_API_TOKEN: ${{ secrets.FLY_ORG_STOPPMO_API_TOKEN }}
  FLY_REGION: bos
  FLY_ORG: stoppmo-490
  FLY_CONFIG_PATH: ./infra/production/fly.production.toml
  FLY_APP_NAME: stoppmo-backend-production
  FLY_SECRETS_PATH: ./infra/production/.env.production

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set App Secrets
        uses: superfly/flyctl-actions@1.5
        with:
          args: 'secrets import < ${{ env.FLY_SECRETS_PATH }} -a ${{ env.FLY_APP_NAME }}'

      - name: Deploy App
        uses: superfly/flyctl-actions@1.5
        with:
          args:
            "deploy --app ${{ env.FLY_APP_NAME }} -c ${{ env.FLY_CONFIG_PATH }}"
