name: Fly Deploy to Production
on:
  push:
    branches:
      - release/production

env:
  FLY_API_TOKEN: ${{ secrets.FLY_ORG_STOPPMO_API_TOKEN }}
  FLY_REGION: bos
  FLY_ORG: stoppmo-490
  FLY_CONFIG_PATH: ./infra/production/fly.production.toml

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Github Repo
        uses: actions/checkout@v4
      - name: Set App Secrets
        uses: superfly/flyctl-actions@1.5
        with:
            args: 'secrets set DATABASE_URL=${{ secrets.PRODUCTION_DATABASE_URL }} ZOHO_CLIENT_ID=${{ secrets.ZOHO_CLIENT_ID }} ZOHO_CLIENT_SECRET=${{ secrets.ZOHO_CLIENT_SECRET }} ZOHO_REFRESH_TOKEN=${{ secrets.ZOHO_REFRESH_TOKEN}} ZOHO_MAIL_AUTH_SENDER_ID=${{ secrets.ZOHO_MAIL_AUTH_SENDER_ID}} --config ${{ env.FLY_CONFIG_PATH }}'

      - name: Deploy App
        uses: superfly/flyctl-actions@1.5
        with:
          args:
            "deploy --config ${{ env.FLY_CONFIG_PATH }}"
