name: Deploy Review App
on:
  # Run this workflow on every PR event. Existing review apps will be updated when the PR is updated.
  pull_request:
    types: [opened, reopened, synchronize, closed]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_ORG_STOPPMO_API_TOKEN }}
  FLY_REGION: bos
  FLY_ORG: stoppmo-490
  FLY_PREVIEW_APP_NAME: stoppmo-backend-pr-${{ github.event.number }}-${{ github.head_ref }}-to-${{ github.base_ref }}
  FLY_PREVIEW_DATABASE_NAME: stoppmo-db-pr-${{ github.event.number }}
  FLY_CONFIG_PATH: ./infra/fly.toml

jobs:
  db:
    if: github.event.action == 'opened' || github.event.action == 'reopened'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Github repo
        uses: actions/checkout@v4
      - name: Create Database
        uses: superfly/flyctl-actions@1.5
        with:
          args:
            'pg create --region ${{ env.FLY_REGION }} --vm-size shared-cpu-1x --name  ${{ env.FLY_PREVIEW_DATABASE_NAME }} --volume-size 5 --org ${{ env.FLY_ORG }} --initial-cluster-size 2'
      - name: Create fly app
        uses: superfly/flyctl-actions@1.1
        with:
          args: "apps create ${{ env.FLY_PREVIEW_APP_NAME }} --org ${{ env.FLY_ORG }}"
      - name: Connect DB to Preview App
        uses: superfly/flyctl-actions@1.5
        env:
          FLY_APP: ${{ env.FLY_PREVIEW_APP_NAME }}
        with:
          args: 'pg attach ${{ env.FLY_PREVIEW_DATABASE_NAME }} --app ${{ env.FLY_PREVIEW_APP_NAME }}'
      - name: Deploy app
        uses: superfly/flyctl-actions@1.5
        with:
          args:
            "deploy --region ${{ env.FLY_REGION }} --app ${{ env.FLY_PREVIEW_APP_NAME }} -c ${{ env.FLY_CONFIG_PATH }}"
      - name: Post link to PR Preview
        uses: actions-ecosystem/action-create-comment@v1
        with:
          github_token: ${{ secrets.github_token }}
          body: Your PR is deployed, see it [here](https://${{ env.FLY_PREVIEW_APP_NAME }}.fly.dev)

  delete_db:
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Github Repo
        uses: actions/checkout@v4
      - name: Delete DB
        uses: superfly/flyctl-actions@1.5
        with:
          args:
            'apps destroy ${{ env.FLY_PREVIEW_DATABASE_NAME }} --yes'

  review_app:
    if: github.event.action != 'opened' || github.event.action != 'reopened'
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.deploy.outputs.url }}
    concurrency:
      group: pr-${{ github.event.number }}
    environment:
      name: review
      url: ${{ steps.deploy.outputs.url }}
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Deploy PR app to Fly.io
        id: deploy
        uses: superfly/fly-pr-review-apps@1.2.1
        with:
          name: ${{ env.FLY_PREVIEW_APP_NAME }}
          config: ${{ env.FLY_CONFIG_PATH }}
